version: "3.3"

services:
  otserver:
    container_name: otserver
    build:
      context: ./
      dockerfile: ./Dockerfile.server
    restart: unless-stopped
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ../:/otserver
    depends_on:
      - otdb

  otdb:
    container_name: otdb
    build:
      context: ./
      dockerfile: ./Dockerfile.database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=otserver
      - MYSQL_USER=otserver
      - MYSQL_PASSWORD=otserver
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
