version: "3.3"

services:
  otserver:
    container_name: otserver
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.server
    restart: unless-stopped
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ot-volume:/opt/otserver
    depends_on:
      - otdb

  otdb:
    container_name: otdb
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.database
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=otserver
      - MYSQL_USER=otserver
      - MYSQL_PASSWORD=otserver
			- MYSQL_ROOT_PASSWORD=otserver
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  otweb:
    container_name: otwebsite
    build:
      context: ./
      dockerfile: ./Dockerfile.web
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "80:80"
    volumes:
      - ot-volume:/opt/otserver
    depends_on:
      - otdb
      - otserver

  otlogin:
    container_name: otwebsite_login
    build:
      context: ./
      dockerfile: ./Dockerfile.login
    restart: unless-stopped
    volumes:
      - ./data/:/tmp/
      - ot-volume:/opt/otserver
    ports:
      - "8080:80"
    depends_on:
      - otdb
      - otserver
			- otweb

volumes:
  db-volume:
  ot-volume:
